#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Nginx2_development

  
test:
  <<: *default
  database: Nginx2_test


production:
  <<: *default
  database: Nginx2_production
  username: Nginx2
  password: <%= ENV['NGINX2_DATABASE_PASSWORD'] %>
